(function($){ var JST = { templates: {} }; JST.templates.multiple = function anonymous(jQuery,$item) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('');if(typeof(JST.templates.multiple_header)!=='undefined' && (JST.templates.multiple_header)!=null){__=__.concat($item.nest(JST.templates.multiple_header,null));}__.push(' <p>This is a sample template</p> ');if(typeof(JST.templates.multiple_foo_bar)!=='undefined' && (JST.templates.multiple_foo_bar)!=null){__=__.concat($item.nest(JST.templates.multiple_foo_bar,null));}__.push('  ');if(typeof(JST.templates.multiple_footer)!=='undefined' && (JST.templates.multiple_footer)!=null){__=__.concat($item.nest(JST.templates.multiple_footer,null));}__.push('');}return __;
}; JST.multiple = function multiple(d){ return $.tmpl( JST.templates.multiple, d ); }; JST.templates.multiple_header = function anonymous(jQuery,$item) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<h1>');if(typeof(title)!=='undefined' && (title)!=null){__.push($.encode((typeof(title)==='function'?(title).call($item):(title))));}__.push('</h1>');}return __;
}; JST.multiple_header = function multiple_header(d){ return $.tmpl( JST.templates.multiple_header, d ); }; JST.templates.multiple_footer = function anonymous(jQuery,$item) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<h1>');if(typeof(title)!=='undefined' && (title)!=null){__.push($.encode((typeof(title)==='function'?(title).call($item):(title))));}__.push('</h1>');}return __;
}; JST.multiple_footer = function multiple_footer(d){ return $.tmpl( JST.templates.multiple_footer, d ); }; JST.templates.multiple_foo_bar = function anonymous(jQuery,$item) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('');if((typeof(foo)!=='undefined' && (foo)!=null) && (typeof(foo)==='function'?(foo).call($item):(foo))){__.push('   ');if(typeof(foo)!=='undefined' && (foo)!=null){$.each((typeof(foo)==='function'?(foo).call($item):(foo)),function($index, $value){with(this){__.push('     <div>');if(typeof($value)!=='undefined' && ($value)!=null){__.push($.encode((typeof($value)==='function'?($value).call($item):($value))));}__.push('</div>   ');}});}__.push(' ');}__.push('');}return __;
}; JST.multiple_foo_bar = function multiple_foo_bar(d){ return $.tmpl( JST.templates.multiple_foo_bar, d ); }; 

JST.templates.sample = function anonymous(jQuery,$item) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<h1>');if(typeof(title)!=='undefined' && (title)!=null){__.push($.encode((typeof(title)==='function'?(title).call($item):(title))));}__.push('</h1> <p>This is a sample template</p> ');if((typeof(foo)!=='undefined' && (foo)!=null) && (typeof(foo)==='function'?(foo).call($item):(foo))){__.push('   ');if(typeof(foo)!=='undefined' && (foo)!=null){$.each((typeof(foo)==='function'?(foo).call($item):(foo)),function($index, $value){with(this){__.push('     <div>');if(typeof(value)!=='undefined' && (value)!=null){__.push($.encode((typeof(value)==='function'?(value).call($item):(value))));}__.push('</div>   ');}});}__.push(' ');}__.push('');}return __;
}; JST.sample = function sample(d){ return $.tmpl( JST.templates.sample, d ); }; window.JST = JST; })(jQuery);